src/main/webapp/resource/page_2/childrenMembership.html
=> 듬린이(어린이회원 11)

src/main/webapp/resource/page_1/login.html, src/main/webapp/resource/page_1/login_pwd.html
=> page_1 비밀번호 찾기 수정

src/main/webapp/resource/css/admin/basket.css, src/main/webapp/resource/page_1/basket.html, src/main/webapp/resource/page_1/basket.jsp, src/main/webapp/resource/page_3/templet.jsp
=> page_1 jsp분리작업중

src/main/webapp/resource/css/common/page4_board.css, src/main/webapp/resource/page_4/boardLeftMenu.jsp, src/main/webapp/resource/page_4/coaching.jsp, src/main/webapp/resource/page_4/dreamsBoarDetail.jsp, src/main/webapp/resource/page_4/dreamsBoard.jsp, src/main/webapp/resource/page_4/dreamsBoardWrite.jsp, src/main/webapp/resource/page_4/news.jsp, src/main/webapp/resource/page_4/playerLeftMenu.jsp, src/main/webapp/resource/page_4/players.jsp, src/main/webapp/resource/page_4/qna.jsp, src/main/webapp/resource/page_4/qnaEtc.jsp, src/main/webapp/resource/page_4/qnaMd.jsp, src/main/webapp/resource/page_4/qnaParking.jsp, src/main/webapp/resource/page_4/qnaSky.jsp, src/main/webapp/resource/page_4/qnaTiket.html, src/main/webapp/resource/page_4/qnaTiket.jsp, src/main/webapp/resource/page_4/stats.jsp, src/main/webapp/resource/page_4/steff.jsp
2024-01-17
헤더, 풋터 jsp 연결 및  html 파일을 jsp 파일로 교체
좌측메뉴바 jsp 추가 및 연결
board css 수정
=> jsp추가, 연결, css 수정

src/main/webapp/resource/css/common/page4_board.css, src/main/webapp/resource/page_4/boardLeftMenu.jsp, src/main/webapp/resource/page_4/dreamsBoarDetail.jsp, src/main/webapp/resource/page_4/dreamsBoard.js, src/main/webapp/resource/page_4/dreamsBoard.jsp, src/main/webapp/resource/page_4/dreamsBoardWrite.jsp, src/main/webapp/resource/page_4/playerLeftMenu.jsp, src/main/webapp/resource/page_4/qna.jsp, src/main/webapp/resource/page_4/qnaEtc.jsp, src/main/webapp/resource/page_4/qnaMd.jsp, src/main/webapp/resource/page_4/qnaParking.jsp, src/main/webapp/resource/page_4/qnaSky.jsp, src/main/webapp/resource/page_4/qnaTiket.jsp, src/main/webapp/resource/page_4/stats.jsp
2024-01-18
jsp 링크 연결 및 자바스크립트 추가
=> 링크연결 및 js 추가

src/main/webapp/resource/page_1/basket.jsp, src/main/webapp/resource/page_1/join.jsp, src/main/webapp/resource/page_1/join_edit.jsp, src/main/webapp/resource/page_1/templet.jsp
=> page_1 join,join_edit jsp로변환완료

src/main/webapp/resource/page_6/Introduce.jsp, src/main/webapp/resource/page_6/deleteMember.jsp, src/main/webapp/resource/page_6/goodsRefund.jsp, src/main/webapp/resource/page_6/location.jsp, src/main/webapp/resource/page_6/modifyMember.jsp, src/main/webapp/resource/page_6/myOrder.jsp, src/main/webapp/resource/page_6/myPage.jsp, src/main/webapp/resource/page_6/parking.jsp, src/main/webapp/resource/page_6/seatRefund.jsp, src/main/webapp/resource/page_6/stadium.jsp
=> page_6 0119 수정

src/main/webapp/resource/page_1/login.jsp, src/main/webapp/resource/page_1/login_id.html, src/main/webapp/resource/page_1/login_id.jsp
=> page_1 jsp분리

src/main/java/pj/mvc/jsp/controller/BoardController.java, src/main/java/pj/mvc/jsp/dto/BoardDTO.java, src/main/webapp/resource/css/common/page4_board.css, src/main/webapp/resource/page_4/dreamsBoard.js, src/main/webapp/resource/page_4/dreamsBoardSearch.jsp
2024-01-22 
mvc 작업 중 
게시판 검색 페이지 추가
main에 올려서 닫고 다시 pl
=> mvc작업 및 게시판검색페이지 추가

src/main/java/pj/mvc/jsp/controller/BoardController.java, src/main/webapp/layout/setting.jsp
24-01-23 setting.xml 추가 및 controller 주소수정
=> 24-01-23 setting.xml 추가 및 controller 주소수정

src/main/java/pj/mvc/jsp/controller/CustomerController.java, src/main/java/pj/mvc/jsp/dao/CustomerDAO.java, src/main/java/pj/mvc/jsp/dao/CustomerDAOImpl.java, src/main/java/pj/mvc/jsp/dto/CustomerDTO.java, src/main/java/pj/mvc/jsp/service/CustomerService.java, src/main/java/pj/mvc/jsp/service/CustomerServiceImpl.java
=> page_6 0123 수정

src/main/webapp/layout/footer.jsp
=> 2024-01-24 commit

.classpath, src/main/webapp/resource/page_1/basket.jsp, src/main/webapp/resource/page_1/join.jsp, src/main/webapp/resource/page_1/join_edit.jsp, src/main/webapp/resource/page_1/login.jsp, src/main/webapp/resource/page_1/login_id.jsp, src/main/webapp/resource/page_1/login_pwd_idCk.html
=> page_1 el태그변환

src/main/java/pj/mvc/jsp/controller/BoardController.java, src/main/java/pj/mvc/jsp/dao/BoardDAO.java, src/main/java/pj/mvc/jsp/dao/BoardDAOImpl.java, src/main/java/pj/mvc/jsp/page/Paging.java, src/main/java/pj/mvc/jsp/service/BoardService.java, src/main/java/pj/mvc/jsp/service/BoardServiceImpl.java, src/main/webapp/resource/css/common/page4_board.css, src/main/webapp/resource/page_4/dreamsBoarDetail.jsp, src/main/webapp/resource/page_4/dreamsBoard.jsp
=> 2024-01-24 수정

src/main/java/pj/mvc/jsp/controller/TicketController.java, src/main/java/pj/mvc/jsp/dao/TicketDAO.java, src/main/java/pj/mvc/jsp/dao/TicketDAOImpl.java, src/main/java/pj/mvc/jsp/dto/TicketDTO.java, src/main/java/pj/mvc/jsp/service/TicketServiceImpl.java, src/main/webapp/layout/header.jsp, src/main/webapp/resource/page_2/purchaseTicket.jsp, src/main/webapp/resource/page_2/ticketFee.jsp
=> .tc로 경로잡기 및 티켓 조회 오류났음 고쳐야함

.classpath, src/main/java/pj/mvc/jsp/controller/OrderController.java, src/main/webapp/resource/page_6/amenity.jsp, src/main/webapp/resource/page_6/deleteMember.jsp, src/main/webapp/resource/page_6/goodsRefund.jsp, src/main/webapp/resource/page_6/location.jsp, src/main/webapp/resource/page_6/myOrder.jsp, src/main/webapp/resource/page_6/myPage.jsp, src/main/webapp/resource/page_6/parking.jsp, src/main/webapp/resource/page_6/stadium.jsp
=> page_6 0125 수정

src/main/java/pj/mvc/jsp/controller/TicketController.java, src/main/java/pj/mvc/jsp/dao/TicketDAO.java, src/main/java/pj/mvc/jsp/dao/TicketDAOImpl.java, src/main/java/pj/mvc/jsp/service/TicketService.java, src/main/java/pj/mvc/jsp/service/TicketServiceImpl.java, src/main/webapp/resource/admin/ticket/ticket detail.html, src/main/webapp/resource/admin/ticket/ticket.jsp, src/main/webapp/resource/admin/ticket/ticket_detail.jsp, src/main/webapp/resource/admin/ticket/ticket_detail_Insert.jsp, src/main/webapp/resource/admin/ticket/ticket_detail_update.jsp, src/main/webapp/resource/page_2/purchaseTicket.jsp, src/main/webapp/resource/page_2/ticketFee.jsp
게시판 페이지를 참고해서 티켓 조회와 수정페이지를 추가해야할 것 같다.
=> 티켓 수정페이지 작성중 감이 안온다..

src/main/java/pj/mvc/jsp/dao/TicketDAOImpl.java, src/main/java/pj/mvc/jsp/service/TicketServiceImpl.java, src/main/webapp/resource/admin/css/ticket.css, src/main/webapp/resource/admin/ticket/ticket_detail.jsp, src/main/webapp/resource/admin/ticket/ticket_detail_Insert.jsp, src/main/webapp/resource/admin/ticket/ticket_detail_update.jsp
=> 티켓추가 티켓삭제 기능 및 페이지 추가

src/main/webapp/resource/page_1/loginAction.jsp, src/main/webapp/resource/page_1/modifyCustomer.jsp
=> page_1 modifyCustomer

src/main/java/pj/mvc/jsp/dao/OrderDAOImpl.java, src/main/java/pj/mvc/jsp/service/OrderServiceImpl.java, src/main/webapp/resource/page_6/goodsRefund.jsp, src/main/webapp/resource/page_6/goodsRefundAction.jsp
=> page_6 0131 수정

src/main/java/pj/mvc/jsp/controller/CustomerController.java, src/main/java/pj/mvc/jsp/dao/CustomerDAOImpl.java, src/main/java/pj/mvc/jsp/dto/CustomerDTO.java, src/main/java/pj/mvc/jsp/service/CustomerServiceImpl.java, src/main/webapp/resource/page_1/loginAction.jsp, src/main/webapp/resource/page_1/modifyCustomerAction.jsp, src/main/webapp/resource/page_1/modifyDetailAction.jsp
=> page_1 회원정보 수정 완료~

src/main/java/pj/mvc/jsp/controller/BoardController.java, src/main/java/pj/mvc/jsp/dao/BoardDAO.java, src/main/java/pj/mvc/jsp/dao/BoardDAOImpl.java, src/main/java/pj/mvc/jsp/dto/Board_reviewDTO.java, src/main/java/pj/mvc/jsp/service/BoardService.java, src/main/java/pj/mvc/jsp/service/BoardServiceImpl.java, src/main/webapp/resource/page_4/dreamsBoardDetail.jsp, src/main/webapp/resource/page_4/dreamsBoardReview.jsp
=> 2024-01-31 수정

src/main/java/pj/mvc/jsp/controller/OrderController.java, src/main/java/pj/mvc/jsp/dao/OrderDAO.java, src/main/java/pj/mvc/jsp/dao/OrderDAOImpl.java, src/main/java/pj/mvc/jsp/dto/OrderDTO.java, src/main/java/pj/mvc/jsp/dto/OrderDetailDTO.java, src/main/java/pj/mvc/jsp/service/OrderServiceImpl.java, src/main/webapp/resource/page_6/myOrder.jsp
page_6 0201 수정
myorders  db에서 읽어오게하기 구현중
=> page_6 0201 수정

src/main/java/pj/mvc/jsp/controller/CustomerController.java, src/main/java/pj/mvc/jsp/dao/CustomerDAOImpl.java, src/main/java/pj/mvc/jsp/service/CustomerServiceImpl.java, src/main/webapp/resource/page_1/deleteCustomer.jsp, src/main/webapp/resource/page_1/deleteCustomerAction.jsp, src/main/webapp/resource/page_1/login.jsp
회원탈퇴 'y' , 'n' 적용 완료
아이디찾기, 비밀번호찾기, 장바구니 남음
=> page_1 회원탈퇴 완료

src/main/java/pj/mvc/jsp/controller/BoardController.java, src/main/java/pj/mvc/jsp/dao/BoardDAO.java, src/main/java/pj/mvc/jsp/dao/BoardDAOImpl.java, src/main/java/pj/mvc/jsp/service/BoardService.java, src/main/java/pj/mvc/jsp/service/BoardServiceImpl.java, src/main/webapp/resource/css/common/page4_board.css, src/main/webapp/resource/page_4/dreamsBoard.js, src/main/webapp/resource/page_4/dreamsBoard.jsp, src/main/webapp/resource/page_4/dreamsBoardDetail.jsp, src/main/webapp/resource/page_4/dreamsBoardReview.jsp, src/main/webapp/resource/page_4/dreamsBoardSearch.jsp
=> 2024-02-01 수정

src/main/java/pj/mvc/jsp/controller/TicketController.java, src/main/java/pj/mvc/jsp/dao/TicketDAO.java, src/main/java/pj/mvc/jsp/dao/TicketDAOImpl.java, src/main/java/pj/mvc/jsp/dto/TicketResDTO.java, src/main/java/pj/mvc/jsp/service/TicketService.java, src/main/java/pj/mvc/jsp/service/TicketServiceImpl.java, src/main/webapp/resource/page_2/ReserationTicket_check.jsp, src/main/webapp/resource/page_2/childrenMembership.jsp, src/main/webapp/resource/page_2/purchaseTicket.jsp
티켓 예매내역 추가중  SQL문 정리 완료, purchase.jsp참고하여 jsp 파일 생성 후 c:foreach 구문 태워야함
=> 티켓 예매내역 추가 SQL문 정리 완료, jsp 파일 생성 후 c:foreach 구문 태워야함

src/main/webapp/resource/page_1/login_pwd.html, src/main/webapp/resource/page_1/login_pwd.jsp, src/main/webapp/resource/page_1/login_pwd_idCk.jsp
=> page_1 아이디찾기 비밀번호찾기(인증은 불가능)

src/main/java/pj/mvc/jsp/controller/TicketController.java, src/main/java/pj/mvc/jsp/service/TicketServiceImpl.java, src/main/webapp/resource/page_2/purchaseTicket.jsp
=> ajax 하는 중 값이 없는 오류 수정해야함

src/main/java/pj/mvc/jsp/controller/BoardController.java, src/main/java/pj/mvc/jsp/dao/BoardDAO.java, src/main/java/pj/mvc/jsp/dao/BoardDAOImpl.java, src/main/java/pj/mvc/jsp/dto/BoardDTO.java, src/main/java/pj/mvc/jsp/dto/Board_reviewDTO.java, src/main/java/pj/mvc/jsp/service/BoardService.java, src/main/java/pj/mvc/jsp/service/BoardServiceImpl.java, src/main/webapp/layout/header.jsp, src/main/webapp/resource/admin/board/board.jsp, src/main/webapp/resource/admin/board/boardDetail.jsp, src/main/webapp/resource/admin/board/boardReview.jsp, src/main/webapp/resource/css/common/page4_board.css, src/main/webapp/resource/page_4/boardLeftMenu.jsp, src/main/webapp/resource/page_4/dreamsBoard.js, src/main/webapp/resource/page_4/dreamsBoard.jsp, src/main/webapp/resource/page_4/dreamsBoardDetail.jsp, src/main/webapp/resource/page_4/news.jsp, src/main/webapp/resource/page_4/stats.jsp
=> 2024-02-05 수정

src/main/java/pj/mvc/jsp/controller/CustomerController.java, src/main/java/pj/mvc/jsp/dao/CustomerDAO.java, src/main/java/pj/mvc/jsp/dao/CustomerDAOImpl.java, src/main/java/pj/mvc/jsp/service/CustomerService.java, src/main/java/pj/mvc/jsp/service/CustomerServiceImpl.java, src/main/webapp/index.jsp, src/main/webapp/layout/header.jsp, src/main/webapp/resource/admin/member/member.jsp, src/main/webapp/resource/admin/member/memberDetail.jsp, src/main/webapp/resource/page_1/login.jsp
관리자모드 작업중
넘버 부분 세팅해야하고
상세내역 내일 가능할듯
=> page_1 관리자모드 작업중

src/main/java/pj/mvc/jsp/controller/OrderController.java, src/main/java/pj/mvc/jsp/dao/OrderDAO.java, src/main/java/pj/mvc/jsp/dao/OrderDAOImpl.java, src/main/java/pj/mvc/jsp/service/OrderService.java, src/main/java/pj/mvc/jsp/service/OrderServiceImpl.java, src/main/webapp/resource/page_6/deleteMember.jsp, src/main/webapp/resource/page_6/goodsRefund.jsp, src/main/webapp/resource/page_6/goodsRefundAction.jsp, src/main/webapp/resource/page_6/myPage.jsp, src/main/webapp/resource/page_6/myTicket.jsp, src/main/webapp/resource/page_6/orderConfirm.jsp, src/main/webapp/resource/page_6/refundDetail.jsp
구매확정 완료
환불신청서 제출, 환불 신청서 조회 진행중
=> page_6 0205 수정

src/main/java/pj/mvc/jsp/service/OrderServiceImpl.java, src/main/webapp/resource/page_6/deleteMember.jsp, src/main/webapp/resource/page_6/goodsRefund.jsp, src/main/webapp/resource/page_6/goodsRefundAction.jsp, src/main/webapp/resource/page_6/modifyMember.jsp, src/main/webapp/resource/page_6/myOrder.jsp, src/main/webapp/resource/page_6/myPage.jsp, src/main/webapp/resource/page_6/myTicket.jsp, src/main/webapp/resource/page_6/orderConfirm.jsp, src/main/webapp/resource/page_6/refundDetail.jsp, src/main/webapp/resource/page_6/ticketRefund.jsp
=> page_6 0206 수정

src/main/webapp/resource/page_4/coaching.jsp, src/main/webapp/resource/page_4/dreamsBoardDetail.jsp, src/main/webapp/resource/page_4/dreamsBoardEdit.jsp, src/main/webapp/resource/page_4/dreamsBoardSearch.jsp, src/main/webapp/resource/page_4/dreamsBoardWrite.jsp, src/main/webapp/resource/page_4/news.jsp, src/main/webapp/resource/page_4/players.jsp, src/main/webapp/resource/page_4/qna.jsp, src/main/webapp/resource/page_4/qnaEtc.jsp, src/main/webapp/resource/page_4/qnaMd.jsp, src/main/webapp/resource/page_4/qnaParking.jsp, src/main/webapp/resource/page_4/qnaSky.jsp, src/main/webapp/resource/page_4/qnaTiket.jsp, src/main/webapp/resource/page_4/stats.jsp, src/main/webapp/resource/page_4/steff.jsp
=> 2024-02-06 수정

src/main/java/pj/mvc/jsp/controller/TicketController.java, src/main/java/pj/mvc/jsp/dao/TicketDAO.java, src/main/java/pj/mvc/jsp/dao/TicketDAOImpl.java, src/main/java/pj/mvc/jsp/dto/TicketResDTO.java, src/main/java/pj/mvc/jsp/service/TicketService.java, src/main/java/pj/mvc/jsp/service/TicketServiceImpl.java, src/main/webapp/resource/page_2/ReserationTicket_check.jsp, src/main/webapp/resource/page_2/purchaseTicket.jsp, src/main/webapp/resource/page_2/ticketFee.jsp
예매 확인 페이지 완료, 관리자 페이지 티켓 구매내역 구현해야함, 티켓 예매확인 DAOImpl SQL구문 수정필요
=> 예매 확인 페이지 완료, 관리자 페이지 티켓 구매내역 구현해야함, 티켓 예매확인 DAOImpl SQL구문 수정필요

src/main/java/pj/mvc/jsp/controller/CustomerController.java, src/main/java/pj/mvc/jsp/dao/CustomerDAO.java, src/main/java/pj/mvc/jsp/dao/CustomerDAOImpl.java, src/main/java/pj/mvc/jsp/dto/CustomerDTO.java, src/main/java/pj/mvc/jsp/service/CustomerService.java, src/main/java/pj/mvc/jsp/service/CustomerServiceImpl.java, src/main/webapp/resource/admin/member/admin_deleteCustomerAction.jsp, src/main/webapp/resource/admin/member/member.js, src/main/webapp/resource/admin/member/member.jsp, src/main/webapp/resource/admin/member/memberDetail.jsp, src/main/webapp/resource/page_1/login.jsp, src/main/webapp/resource/page_1/loginAction.jsp
=> page_1 관리자모드 상세목록작업중

src/main/java/pj/mvc/jsp/dao/BoardDAO.java, src/main/java/pj/mvc/jsp/dao/BoardDAOImpl.java, src/main/java/pj/mvc/jsp/service/BoardServiceImpl.java, src/main/webapp/resource/page_4/dreamsBoardDetail.jsp
=> 2024-02-07 수정

src/main/java/pj/mvc/jsp/controller/OrderController.java, src/main/java/pj/mvc/jsp/dao/OrderDAO.java, src/main/java/pj/mvc/jsp/dao/OrderDAOImpl.java, src/main/java/pj/mvc/jsp/service/OrderService.java, src/main/java/pj/mvc/jsp/service/OrderServiceImpl.java, src/main/webapp/resource/page_6/goodsRefund.jsp, src/main/webapp/resource/page_6/goodsRefundAction.jsp, src/main/webapp/resource/page_6/myOrder.jsp, src/main/webapp/resource/page_6/myPage.jsp, src/main/webapp/resource/page_6/refundDetail.jsp
=> page_6 0207 수정

src/main/java/pj/mvc/jsp/controller/CustomerController.java, src/main/java/pj/mvc/jsp/dao/CustomerDAO.java, src/main/java/pj/mvc/jsp/dao/CustomerDAOImpl.java, src/main/java/pj/mvc/jsp/dto/CustomerDTO.java, src/main/java/pj/mvc/jsp/service/CustomerService.java, src/main/java/pj/mvc/jsp/service/CustomerServiceImpl.java, src/main/webapp/resource/admin/member/admin_recoverCustomerAction.jsp, src/main/webapp/resource/admin/member/admin_suspendCustomerAction.jsp, src/main/webapp/resource/admin/member/member.js, src/main/webapp/resource/admin/member/member.jsp, src/main/webapp/resource/admin/member/memberDetail.jsp
=> page_1 관리자모드 페이징처리

src/main/java/pj/mvc/jsp/controller/BoardController.java, src/main/java/pj/mvc/jsp/dao/BoardDAOImpl.java, src/main/java/pj/mvc/jsp/dto/BoardDTO.java, src/main/java/pj/mvc/jsp/dto/Board_reviewDTO.java, src/main/java/pj/mvc/jsp/service/BoardServiceImpl.java, src/main/webapp/layout/header.jsp, src/main/webapp/resource/admin/board/board.jsp, src/main/webapp/resource/admin/board/boardDetail.jsp, src/main/webapp/resource/css/common/page4_board.css, src/main/webapp/resource/page_4/dreamsBoard.jsp, src/main/webapp/resource/page_4/dreamsBoardDetail.jsp, src/main/webapp/resource/page_4/dreamsBoardWrite.jsp
=> 2024-02-08 수정

src/main/java/pj/mvc/jsp/dao/CustomerDAO.java, src/main/java/pj/mvc/jsp/dao/CustomerDAOImpl.java, src/main/java/pj/mvc/jsp/service/CustomerService.java, src/main/java/pj/mvc/jsp/service/CustomerServiceImpl.java, src/main/webapp/resource/admin/member/member.jsp, src/main/webapp/resource/admin/templet/nav.jsp, src/main/webapp/resource/page_1/deleteCustomer.jsp, src/main/webapp/resource/page_1/idConfirmAction.jsp, src/main/webapp/resource/page_1/join.js, src/main/webapp/resource/page_1/join.jsp, src/main/webapp/resource/page_1/joinAction.jsp, src/main/webapp/resource/page_1/loginAction.jsp, src/main/webapp/resource/page_1/modifyDetailAction.jsp
=> page_1 재가입, 연락처,비번체크 완료

dreams_query.sql, src/main/webapp/resource/page_6/amenity.jsp, src/main/webapp/resource/page_6/refundDetail.jsp
=> page_6 amenity 부트스트랩적용

src/main/java/pj/mvc/jsp/controller/BoardController.java
=> 2024-02-16 관리자소스수정
